server:
  port: 9002
spring:
  redis:
    host: 192.168.37.128
    port: 6379
    timeout: 30s
  datasource:
    user:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      name: user
      url: jdbc:mysql://192.168.37.128:3306/user?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    admin:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      name: admin
      url: jdbc:mysql://192.168.37.128:3306/admin?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    book:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      name: book
      url: jdbc:mysql://192.168.37.128:3306/book?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.tigrex.user.entity
  check-config-location: false
logging:
  config: classpath:logback-spring.xml